- hosts: all
  become: yes
  tasks:
  - name: 添加kibana软件源
    copy: 
      src: kibana.repo
      dest: /etc/yum.repos.d/kibana.repo
    notify: yum-clean-metadata

  - name: 安装kibana
    yum:
      name: kibana
      state: installed
    notify: enable-kibana-service

  - name: 配置kibana
    copy: 
      src: conf/kibana.yml
      dest: /etc/kibana/kibana.yml
    notify: restart-kibana-service
    
  handlers:
  - name: yum-clean-metadata
    command: yum clean metadata
    args:
      warn: no

  - name: enable-kibana-service
    service:
      name: kibana
      enabled: yes

  - name: restart-kibana-service
    service:
      name: kibana
      state: restarted
