---
# defaults file for redis
redis_version: 6.2.2
redis_package_filename: redis-{{ redis_version }}.tar.gz
source_base_dir: /data/src
redis_user: redis
redis_install_dir: /data/app/redis
redis_source_dir: "{{ source_base_dir }}/redis-{{ redis_version }}/"

