---
- hosts: all
  become: yes
  tasks:
    - name: Step 1 installs some necessary system tools
      command: yum install -y yum-utils device-mapper-persistent-data lvm2
      args:
        warn: no
    
    - name: Step 2 add software source information
      command: yum-config-manager --add-repo https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
    
    - name: Step 3 update and install docker CE
      command: "{{ item }}"
      with_items:
        - yum makecache fast
        - yum -y install docker-ce
      args:
        warn: no
    
    - name: Step 4 enable and start docker service
      service:
        name: docker
        state: started
        enabled: yes
