---
- hosts: all
  become: yes
  tasks:
    - name: Step 1 installs some necessary system tools
      command: yum install -y yum-utils device-mapper-persistent-data lvm2
      args:
        warn: no
    
    - name: Step 2 add software source information
      command: yum-config-manager --add-repo https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
    
    - name: Step 3 update and install docker CE
      command: "{{ item }}"
      with_items:
        - yum makecache fast
        - yum -y install docker-ce-19.03.15
      args:
        warn: no

    - name: 创建文件夹
      file:
        path: /etc/docker
        state: directory
    
    - name: step 4 docker 国内镜像加速
      template:
        src: daemon.json
        dest: /etc/docker/daemon.json
    
    - name: Step 5 enable and start docker service
      service:
        name: docker
        state: restarted
        enabled: yes
