---
# tasks file for redis
- name: 创建目录结构
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /data/app
    - /data/src

- name: 安装依赖
  yum:
    name: systemd-devel
    state: present

- name: 解压源码包
  unarchive:
    src: "{{ redis_package_filename }}"
    dest: "{{ source_base_dir }}"

- name: 添加用户
  user:
    name: "{{ redis_user }}"

- name: 编译安装
  command:
    cmd: "{{ item }}"
    chdir: "{{ redis_source_dir }}"
  with_items:
    - "make USE_SYSTEMD=yes"
    - "make install PREFIX={{ redis_home }}"

- name: 生成目录结构
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ redis_user }}"
    group: "{{ redis_user }}"
    mode: "0755"
  with_items:
    - "{{ redis_home }}/data/"
    - "{{ redis_home }}/sentinel_data/"
    - "{{ redis_home }}/etc/"
    - "{{ redis_home }}/run/"
    - "{{ redis_home }}/log/"

- name: 生成redis-server配置文件
  template:
    src: redis.conf.j2
    dest: "{{ redis_home }}/etc/redis.conf"
    owner: "{{ redis_user }}"
    group: "{{ redis_user }}"

- name: 生成自启动文件
  template:
    src: redis.service.j2
    dest: "/usr/lib/systemd/system/redis.service"

- name: 生成redis-sentinel配置文件
  template:
    src: sentinel.conf.j2
    dest: "{{ redis_home }}/etc/sentinel.conf"
    owner: "{{ redis_user }}"
    group: "{{ redis_user }}"

- name: 生成redis-sentinel自启动文件
  template:
    src: redis-sentinel.service.j2
    dest: "/usr/lib/systemd/system/redis-sentinel.service"

- name: 添加环境变量配置文件
  template:
    src: redis.sh.j2
    dest: "/etc/profile.d/redis.sh"

- name: 内核参数优化
  sysctl:
    name: net.core.somaxconn
    value: "1024"

- sysctl:
    name: vm.overcommit_memory
    value: "1"

- name: 设置开机启动 & 重启  
  systemd:
    name: redis
    state: restarted
    daemon_reload: yes
    enabled: yes
